// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial1_Ap2_Garcia.DAL;

namespace Parcial1_Ap2_Garcia.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Parcial1_Ap2_Garcia.Models.Articulos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Inventario")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("articulos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Costo = 345.34m,
                            Descripcion = "Mouse Inalambrico",
                            Existencia = 34,
                            Inventario = 11741.56m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
